# Generated by Django 5.0.1 on 2024-01-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=254, null=True)),
                ('datil', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(blank=True, max_length=255, null=True)),
                ('datil', models.TextField()),
                ('many', models.IntegerField()),
                ('price', models.IntegerField()),
                ('categotory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.company')),
            ],
        ),
    ]
