# Generated by Django 5.0.1 on 2024-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imag_product',
            field=models.ImageField(upload_to='Product/'),
        ),
    ]
