# Generated by Django 5.0.1 on 2024-01-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_imag_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='imag_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.imageforproduct'),
        ),
    ]
