# Generated by Django 5.0.1 on 2024-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_imageforproduct_alter_product_imag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforproduct',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='product',
            name='imag_product',
        ),
        migrations.AddField(
            model_name='product',
            name='imag_product',
            field=models.ManyToManyField(to='Product.imageforproduct'),
        ),
    ]
