# Generated by Django 5.0.1 on 2024-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_carousel_url', models.ImageField(upload_to='apps/main/images/')),
                ('img_carousel_title', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
