# Generated by Django 5.0.1 on 2024-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimg',
            name='img_carousel_url',
            field=models.ImageField(upload_to='main/'),
        ),
    ]
