# Generated by Django 5.0.1 on 2024-02-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
