# Generated by Django 5.0.1 on 2024-02-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_onetimeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeurl',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 10, 17, 48, 150595, tzinfo=datetime.timezone.utc)),
        ),
    ]
